### ISSUE TITLE
running mix ecto.create   =>  /user_controller.ex:63: warning: variable jwt is unused

### ISSUE THREAD

**Issue by evorel** [ryanswapp/react-phoenix-starter-template#4]
Any ideas on the error below? Thanks

web/controllers/v1/user_controller.ex:63: warning: variable jwt is unused

== Compilation error on file web/controllers/v1/user_controller.ex ==
*\* (CompileError) web/controllers/v1/user_controller.ex:68: function user/0 undefined
    (stdlib) lists.erl:1337: :lists.foreach/2
    (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8

**Comment by ryanswapp** [comment]
Ya sorry about that. We recently changed the Guardian code and a bug slipped in! The current_user function in the user_controller should look like this:

```
def current_user(conn, %{"jwt" => jwt}) do
    case Guardian.Plug.current_resource(conn) do
      nil -> 
        conn
        |> put_status(:not_found)
        |> render(ReactPhoenix.V1.SessionView, "error.json", error: "User not found")
      user ->
        conn
        |> put_status(:ok)
        |> render("show.json", user: user)
    end
  end
```

I'm pushing a fix now.

**Comment by evorel** [comment]
Thanks Ryan. Nice work

**Comment by ryanswapp** [comment]
No Problem! Happy to help. Let me know if you find any other rough edges :)
