### ISSUE TITLE
Loading Images

### ISSUE THREAD

**Issue by brandonmikeska** [ryanswapp/react-phoenix-starter-template#9]
Hey since the projects are broken up, how do you plan on handling images inside of css and inline for react?

**Comment by ryanswapp** [comment]
Lately I've been storing images on S3 and then pulling them into my apps as needed. You could also store them on some other CDN. You can put them in your phoenix app if you'd like, you'd just have to reference them by their absolute URL.

**Comment by AdamBrodzinski** [comment]
+1 a CDN is an order of magnitude better. There are even grunt/brunch scripts you can run to upload them to S3 automatically (syncing).

**Comment by brandonmikeska** [comment]
Thanks guys. I was thinking of just putting them on my s3 bucket, just a little different workflow than I am currently used to, but makes sense as this isn't your .NET MVC or Rails application.
